# Generated by Django 3.2.3 on 2021-06-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0004_publusher_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название книги')),
                ('picture', models.ImageField(upload_to='books/', verbose_name='Фото обложки')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена (BYN)')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество в наличии')),
                ('desription', models.TextField(blank=True, null=True, verbose_name='Об авторе')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='dictionaries.author')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
