# Generated by Django 3.2.3 on 2021-06-24 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_publusher_picture'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='desription',
        ),
        migrations.AddField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный (доступен для заказа, Да/Нет)'),
        ),
        migrations.AddField(
            model_name='book',
            name='age_stop',
            field=models.CharField(default=0, max_length=10, verbose_name='Возрастные ограничения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.CharField(default=0, max_length=10, verbose_name='Переплет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.CharField(default=0, max_length=10, verbose_name='Формат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата внесения в каталог'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='dictionaries.bookgenre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=1, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=1, verbose_name='Страниц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publusher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='dictionaries.publusher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=7, verbose_name='Рейтинг (0 - 10)'),
        ),
        migrations.AddField(
            model_name='book',
            name='serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='dictionaries.bookseries'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес (гр)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Год издания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество книг в наличии'),
        ),
    ]
