# Generated by Django 3.2.3 on 2021-06-25 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_agestop_binding_bookformat_rating'),
        ('books', '0002_auto_20210624_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.agestop', verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.binding', verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.bookformat', verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=9783000000000, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.rating', verbose_name='Рейтинг (0 - 10)'),
        ),
    ]
