# Generated by Django 3.2.3 on 2021-06-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0007_alter_rating_variant'),
        ('books', '0003_auto_20210625_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='dictionaries.Author'),
        ),
    ]
