# Generated by Django 3.2.3 on 2021-06-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0007_alter_rating_variant'),
        ('books', '0004_auto_20210625_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='dictionaries.BookGenre'),
        ),
    ]
