# Generated by Django 3.2.3 on 2021-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210625_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_orders',
            field=models.IntegerField(default=0, verbose_name='Количество заказов'),
        ),
    ]
