# Generated by Django 3.2.3 on 2021-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Фамилия.И.О автора')),
                ('desription', models.TextField(blank=True, null=True, verbose_name='Фамилия.И.О автора')),
            ],
        ),
    ]
