# Generated by Django 3.2.3 on 2021-05-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название жанра')),
                ('desription', models.TextField(blank=True, null=True, verbose_name='Описание жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название серии')),
                ('desription', models.TextField(blank=True, null=True, verbose_name='Описание серии')),
            ],
            options={
                'verbose_name': 'Книжная серия',
                'verbose_name_plural': 'Книжные серии',
            },
        ),
        migrations.CreateModel(
            name='Publusher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название издательства')),
                ('desription', models.TextField(blank=True, null=True, verbose_name='Описание издательства')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterField(
            model_name='author',
            name='desription',
            field=models.TextField(blank=True, null=True, verbose_name='Об авторе'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Фамилия.И.О автора'),
        ),
    ]
