# Generated by Django 3.2.3 on 2021-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20210523_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(default=112, upload_to='authors/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Фамилия.И.О автора'),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='publusher',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название издательства'),
        ),
    ]
