# Generated by Django 3.2.3 on 2021-06-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_auto_20210608_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='publusher',
            name='picture',
            field=models.ImageField(default=5454, upload_to='publishers/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
