# Generated by Django 3.2.3 on 2021-06-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_agestop_binding_bookformat_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='variant',
            field=models.IntegerField(default=7, verbose_name='Рейтинг (0 - 10)'),
        ),
    ]
