# Generated by Django 3.2.3 on 2021-06-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0006_alter_rating_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='variant',
            field=models.IntegerField(verbose_name='Рейтинг (0 - 10)'),
        ),
    ]
