print('Необходимо ввести 3 целых числа')
a = int(input('Число a = '))
b = int(input('Число b = '))
c = int(input('Число c = '))
print(a and b and c and "Нет нулевых значений!!!")
print(a or b or c or "Введены все нули!")
print(a > b + c and a - b - c)
print(a < b + c and b + c - a)
print(a > 50 and (b > 50 or c > 50) and 'Вася')
print((a > 5 or b == c == 7) and 'Петя')