# Generated by Django 3.2.3 on 2021-07-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_num_orders'),
        ('carts', '0003_auto_20210630_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='books.book', verbose_name='Книга'),
        ),
    ]
