# Generated by Django 3.2.3 on 2021-06-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс'),
        ),
    ]
