# Generated by Django 3.2.3 on 2021-07-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0008_status'),
        ('carts', '0003_auto_20210630_1230'),
        ('orders', '0002_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=5486, max_length=15, verbose_name='Телефон пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.status', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='carts.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Контактная информация'),
        ),
    ]
