# Generated by Django 3.2.3 on 2021-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=30, verbose_name='Имя пользователя'),
        ),
    ]
